apiVersion: v1
kind: Service
metadata:
  name: pets-app
  labels:
    app: pets-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
  selector:
    app: pets-app

